-- SQL Migration Script to add 'deleted' field to all tables
-- Compatible with PostgreSQL (safely checks IF NOT EXISTS)

ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE income_configs ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE lend_borrows ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE repayments ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE investments ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE category_budgets ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE od_accounts ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE od_transactions ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE fuel_logs ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE vehicle_configs ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE car_trips ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
